[package]
name = "rapier_godot_scene_loader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
rapier3d = "0.18.0"
serde_json = "1.0.114"
